name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    # uses: ./.github/workflows/reusable-workflow-example-caller.yml
    runs-on: ubuntu-latest
    steps:
      - id: do-a-thing
        run: echo "ran!"
