
name: Called reusable workflow

on:
  workflow_call:
    inputs:
      BUILD_ENV:
        required: true
        type: string
    secrets:
      TESTING:
        required: true

jobs:
  called-workflow:
    name: Blippedy
    runs-on: ubuntu-latest
    steps:
      - id: do-a-thing
        run: echo "${BUILD_ENV} is ${TESTING}!"
