
name: Called reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  called-workflow:
    name: Blippedy
    runs-on: ubuntu-latest
    steps:
      - id: do-a-thing
        run: echo "${username}!"
