
name: Reusable workflow example

on:
  workflow_call:
    # inputs:
    #   username:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  called-workflow:
    # uses: ./.github/workflows/reusable-workflow-example-caller.yml
    runs-on: ubuntu-latest
    steps:
      - id: do-a-thing
        run: echo "ran!"
