name: Caller for a reusable workflow
on:
  push:
    branches:
      - main
jobs:
  example_job:
    uses: ./.github/workflows/reusable-workflow-example-called.yml
    with:
      BUILD_ENV: Dev
    secrets:
      TESTING: ${{ secrets.TESTING }}
