name: Run On Tag

on:
  push:
    tags:
      - run-on-tag
      - v1.0.1

jobs:
  run-on-tag:
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: echo-working
        run: |
          echo "Working!"