name: Test qualities of the environment

# Runs when a merge request is closed on the deploy branch
on: push

jobs:
  test-props:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        # if: ${{ env.STRING }}
        shell: bash
        run: |
          
          pwd
          ls -alh

          if ${{ github.ref == 'refs/heads/master' }} ;then
            echo "runs!"
          fi
