name: Test string secrets

# Runs when a merge request is closed on the deploy branch
on: push

jobs:
  test-string-compare:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-5.3-xenial
    env:
      STRING: ${{ secrets.STRING == 'string' }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        if: ${{ env.STRING }}
        run: echo "passes!"
  test-if-expressions:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-5.3-xenial
    env:
      ENV_VAR_RAW: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE }}
      ENV_VAR_BOOL: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE == 'istrue' }}
    steps:
    - uses: actions/checkout@v2
    - name: test_3
      id: test_3
      if: ${{ env.ENV_VAR_RAW == 'istrue' }}
      run: |
        echo "env.ENV_VAR_RAW == istrue \"env.ENV_VAR_RAW\""
    - name: test_4
      id: test_4
      shell: bash
      run: |
        set -x
        echo "true: ${{ true }}"
        if [ ${{ true }} ]; then
          echo "true expression with test"
        fi
        if ${{ true }}; then
          echo "true expression"
        fi
    - name: test_7
      id: test_7
      if: ${{ env.ENV_VAR_BOOL }}
      run: echo "good"
    

  determine-value:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-5.3-xenial
    # needs: previous_step which runs the tests...
    env:
      SHOULD_DEPLOY: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE }}
    steps:
    - uses: actions/checkout@v2
    - name: test_1
      id: test_1
      # TODO: Add success(): Returns true when none of the previous steps have failed or been canceled
      # && if merge pr
      if: ${{ env.SHOULD_DEPLOY == 'istrue' }}
      run: | 
        echo "ran!"
        if [ $SHOULD_DEPLOY = "istrue" ]; then
          echo "expression also checks out here"
        elif [ $SHOULD_DEPLOY = "isfalse" ]; then
          echo "Does not check out expression" >&2
        else
          echo "does not compute" >&2
        fi
      shell: bash