name: Learn about GHActions

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2-xenial
    steps:
    - uses: actions/checkout@v2
    - name: test things!
      run: | 
        set -x
        bash --version
        # Show OS info:
        cat /etc/os-release
        uname --kernel-name --kernel-release --machine

        # List possible shells
        cat /etc/shells

        # Get more info about the shell that's running
        ps -p $$
        echo $0
        echo $SHELL
        
        # shopt doesn't seem to work, so workaround it
        LIST=(*bar*)
        echo "$LIST"
        if [ "$LIST" = "*bar*" ]; then
          unset LIST
        fi
        echo $LIST

        LIST=(b*)
        echo $LIST
      shell: bash


