name: Learn about GHActions

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2-xenial
    steps:
    - uses: actions/checkout@v2
    - name: test things!
      run: | 
        set -x
        bash --version
        cat /etc/os-release
        uname --kernel-name --kernel-release --machine
        shopt -s nullglob
        ls /