name: Learn about GHActions

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-latest
    container:
      image: swift:5.2-xenial
    steps:
    - uses: actions/checkout@v2
    - name: test things!
      run: | 
        set -x
        bash --version
        # Show OS info:
        cat /etc/os-release
        uname --kernel-name --kernel-release --machine

        # List possible shells
        cat /etc/shells

        # Get more info about the shell that's running
        ps -p $$
        echo $0
        echo $SHELL
        
        shopt -s nullglob
        cd /
        LIST=(*bar*)

        [ -z "$LIST" ] && echo "Empty"
        echo "$LIST"
        
        LISTY=(*b*)
        echo ${LISTY[@]}

        LISTZ=*b*
        echo $LISTZ

      shell: bash
  sshable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
  finish:
    runs-on: ubuntu-latest
    steps:
    - name: final
      run: echo "done"